# Generated by Django 6.0.4 on 2026-04-25 05:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_artist', models.BooleanField(db_index=True, default=False)),
                ('artist_color', models.CharField(default='#ffffff', max_length=7)),
                ('is_pro', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('points', models.PositiveIntegerField(db_index=True, default=0)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('last_active', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_plays', models.PositiveIntegerField(db_index=True, default=0)),
                ('groups', models.ManyToManyField(blank=True, related_name='music_customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='music_customuser_permissions', to='auth.permission')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlist_covers/')),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Tickets', 'Event Tickets'), ('Digital', 'Digital Downloads'), ('Other', 'Other Merch')], db_index=True, default='Clothing', max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('genre', models.CharField(choices=[('Afrobeat', 'Afrobeat'), ('Dancehall', 'Dancehall'), ('Gospel', 'Gospel'), ('Kadongo Kamu', 'Kadongo Kamu'), ('Hip Hop', 'Hip Hop'), ('R&B', 'R&B'), ('Amapiano', 'Amapiano'), ('Reggae', 'Reggae'), ('Zouk', 'Zouk'), ('Highlife', 'Highlife'), ('Soukous', 'Soukous'), ('Bongo Flava', 'Bongo Flava'), ('pop', 'Pop')], db_index=True, default='Afrobeat', max_length=50)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('play_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(db_index=True, default=False)),
                ('trending_expiry', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('boost_paid', models.BooleanField(default=False)),
                ('boost_requested_at', models.DateTimeField(blank=True, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(blank=True, related_name='song_favorites', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='song_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='music.playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='music.song')),
            ],
            options={
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-points'], name='music_custo_points_6bb2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['-last_active'], name='music_custo_last_ac_a0af7f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_artist', '-points'], name='music_custo_is_arti_1741e4_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user', '-created_at'], name='music_playl_user_id_0f2ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['is_public', '-play_count'], name='music_playl_is_publ_0f54a4_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['name'], name='music_playl_name_a9410d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['artist', '-created_at'], name='music_produ_artist__ec173d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', '-created_at'], name='music_produ_categor_62e71b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-sold_count'], name='music_produ_sold_co_862017_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-play_count'], name='music_song_play_co_4fba2a_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre', '-play_count'], name='music_song_genre_90a7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist', '-created_at'], name='music_song_artist__74f101_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_trending', '-trending_expiry'], name='music_song_is_tren_055668_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_approved', '-created_at'], name='music_song_is_appr_7048ec_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='music_song_title_8e56ff_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyplayed',
            index=models.Index(fields=['user', '-played_at'], name='music_recen_user_id_3cb9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyplayed',
            index=models.Index(fields=['song', '-played_at'], name='music_recen_song_id_e06f25_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyplayed',
            index=models.Index(fields=['-played_at'], name='music_recen_played__a48bea_idx'),
        ),
        migrations.AddConstraint(
            model_name='recentlyplayed',
            constraint=models.UniqueConstraint(fields=('user', 'song'), name='unique_user_song_once'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together={('playlist', 'song')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['song', '-created_at'], name='music_comme_song_id_161c28_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='music_comme_user_id_41af63_idx'),
        ),
    ]
