# Generated by Django 6.0.4 on 2026-05-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_customuser_pro_expiry_customuser_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'Regular User'), ('artist', 'Artist')], default='user', max_length=10),
        ),
    ]
