# Generated by Django 6.0.3 on 2026-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ad_type', models.CharField(choices=[('sponsor', 'Sponsor Ad (Sidebar)'), ('banner', 'Banner Ad (Top/Bottom)'), ('infeed', 'In-Feed Ad (Between Songs)'), ('event', 'Event Ad')], default='sponsor', max_length=20)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link_url', models.URLField(help_text='Where users go when they click the ad')),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers show first')),
                ('advertiser_name', models.CharField(max_length=200)),
                ('advertiser_contact', models.CharField(help_text='WhatsApp or Phone number', max_length=100)),
                ('advertiser_email', models.EmailField(blank=True, max_length=254)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
