# Generated by Django 6.0.3 on 2026-05-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='advertiser_business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='advertiser_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name shown on your profile', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wants_to_advertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
