# Generated by Django 6.0.3 on 2026-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_customuser_advertiser_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='region',
            field=models.CharField(blank=True, default='all', max_length=50),
        ),
    ]
