# Generated by Django 6.0.3 on 2026-05-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('dj_name', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='dj_mixes/')),
                ('audio_file', models.FileField(upload_to='dj_mixes/audio/')),
                ('duration', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-release_date'],
            },
        ),
    ]
