# Generated by Django 6.0.3 on 2026-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_djmix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('host_name', models.CharField(blank=True, default='Unknown Host', max_length=100, null=True)),
                ('cover_image', models.ImageField(upload_to='podcasts/covers/')),
                ('audio_file', models.FileField(upload_to='podcasts/audio/')),
                ('duration', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('episode_number', models.IntegerField(default=1)),
                ('season_number', models.IntegerField(default=1)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-season_number', '-episode_number', '-release_date'],
            },
        ),
    ]
