# Generated by Django 6.0.4 on 2026-05-16 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('play_duration', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', '-played_at'], name='music_userl_user_id_9bd177_idx'), models.Index(fields=['song', '-played_at'], name='music_userl_song_id_781291_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSongInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('play', 'Play'), ('like', 'Like'), ('favorite', 'Favorite'), ('download', 'Download'), ('share', 'Share'), ('skip', 'Skip')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'interaction_type'], name='music_users_user_id_6ae6b6_idx'), models.Index(fields=['song', 'interaction_type'], name='music_users_song_id_376605_idx')],
            },
        ),
    ]
