# Generated by Django 6.0.3 on 2026-05-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_userlisteninghistory_usersonginteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video link (e.g., https://www.youtube.com/watch?v=...', null=True),
        ),
    ]
