# Generated by Django 6.0.3 on 2026-05-17 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_song_has_video_song_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix_type', models.CharField(choices=[('daily', 'Daily Mix'), ('weekly', 'Weekly Mix'), ('genre', 'Genre Mix')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='mix_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MixSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_songs', to='music.usermix')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
