# Generated by Django 6.0.3 on 2026-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='has_lyrics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
