# Generated by Django 6.0.3 on 2026-05-22 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_alter_comment_options_comment_is_edited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly - UGX 20,000'), ('yearly', 'Yearly - UGX 200,000')], max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='pro_payments/')),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
