# Generated by Django 6.0.4 on 2026-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_payment_earning_usersongpurchase_wallet_withdrawal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('uganda', '🇺🇬 Uganda'), ('kenya', '🇰🇪 Kenya'), ('tanzania', '🇹🇿 Tanzania'), ('rwanda', '🇷🇼 Rwanda'), ('burundi', '🇧🇮 Burundi'), ('south_sudan', '🇸🇸 South Sudan'), ('other', '🌍 Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='country',
            field=models.CharField(blank=True, choices=[('uganda', '🇺🇬 Uganda'), ('kenya', '🇰🇪 Kenya'), ('tanzania', '🇹🇿 Tanzania'), ('rwanda', '🇷🇼 Rwanda'), ('burundi', '🇧🇮 Burundi'), ('south_sudan', '🇸🇸 South Sudan'), ('other', '🌍 Other')], max_length=50, null=True),
        ),
    ]
