# Generated by Django 6.0.4 on 2026-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_customuser_city_customuser_country_song_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersongpurchase',
            name='downloads_remaining',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersongpurchase',
            name='has_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
