# Generated by Django 6.1.1 on 2026-09-11 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_alter_ad_id_alter_comment_id_alter_commentlike_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username. Letters, digits, spaces, and @/./+/-/_ only.', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
